### PR TITLE
🚀 RELEASE: v0.1.0 Alpha

### PR DESCRIPTION
**Pull request by warengonzaga**
Alpha version of the Directory web application.

### CODE REVIEW

**Comment by warengonzaga** [comment]
@john-revzoom it result into this error.
image

can you double-check? when I do `yarn dev`

**Comment by jnebab** [comment]
> @john-revzoom it result into this error. image
> 
> can you double-check? when I do `yarn dev`

I made another PR to fix this [here.](https://github.com/web3phl/directory/pull/5) sorry for not testing it properly earlier.

**Comment by warengonzaga** [comment]
Hey, @john-revzoom kindly remove the commit lint as I have my own convention for this.
I'll share in the discussion for the correct convention.

**Comment by warengonzaga** [comment]
Hey, @john-revzoom here's the suggested convention for a commit message.
#7 if you can implement this to the commitlint that would be great!

**Comment by jnebab** [comment]
image


> Hey, @john-revzoom here's the suggested convention for a commit message. #7 if you can implement this to the commitlint that would be great!

tried it but having issue on rendering the ☕. not sure if this is VSCode issue though. and use this account to tag me - @jnebab. Thanks :)

image

**Comment by kquirapas** [comment]
@warengonzaga @jnebab Great work with the progress kita mostly config naman so LGTM

**Review by kquirapas — APPROVED** [review]
Mostly boilerplate, config, and linting changes. LGTM

**Comment by warengonzaga** [comment]
> > Hey, @john-revzoom here's the suggested convention for a commit message. #7 if you can implement this to the commitlint that would be great!
> 
> hi sir @warengonzaga, tried it but having issue on rendering the ☕. not sure if this is VSCode issue though. Will need to explore more. and kindly use this account to tag me please - @jnebab. Thanks :)
> 
> image

amazing implementation! LPG 🔥

**Pull request merged**
