### PR TITLE
📦 NEW: add instagram based routing for viewing directory details/card

### PR DESCRIPTION
**Pull request by jnebab**
#43

### CODE REVIEW

**Comment by warengonzaga** [comment]
Moved this to #35

**Comment by warengonzaga** [comment]
Can you take a look into this @kquirapas? should we merge this with v1.2 update?

**Comment by warengonzaga** [comment]
@kquirapas can you check if this is a good addition?

**Comment by warengonzaga** [comment]
@jnebab can you fix the conflict?

**Comment by jnebab** [comment]
closing this for now. no time to fix and update

**Pull request closed without merging**
